"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { StaffNav } from "./staff-nav";
import styles from "./staff-console.module.css";

type Promotion={id:string;name:string;description:string|null;discountType:"PERCENTAGE"|"FIXED_AMOUNT";value:number;minSubtotalCents:number;maxDiscountCents:number|null;startsAt:string|null;endsAt:string|null;priority:number;isActive:boolean;productIds:string[];categoryIds:string[]};
type Option={id:string;name:string};
type Draft={name:string;description:string;discountType:"PERCENTAGE"|"FIXED_AMOUNT";value:string;minSubtotal:string;maxDiscount:string;startsAt:string;endsAt:string;priority:string;isActive:boolean;productIds:string[];categoryIds:string[]};
const blank:Draft={name:"",description:"",discountType:"PERCENTAGE",value:"10",minSubtotal:"0",maxDiscount:"",startsAt:"",endsAt:"",priority:"0",isActive:true,productIds:[],categoryIds:[]};
const cents=(v:string)=>Math.round((Number(v||"0")||0)*100); const dt=(v:string|null)=>v?v.slice(0,16):"";
export function AutomaticPromotionsManager(){
 const [items,setItems]=useState<Promotion[]>([]),[products,setProducts]=useState<Option[]>([]),[categories,setCategories]=useState<Option[]>([]),[draft,setDraft]=useState<Draft>(blank); const [editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{const [a,p,c]=await Promise.all([fetch("/api/staff/promotions/automatic",{cache:"no-store"}),fetch("/api/staff/catalog",{cache:"no-store"}),fetch("/api/staff/categories",{cache:"no-store"})]); const ab=await a.json().catch(()=>null); if(!a.ok) throw new Error(ab?.message??"Unable to load automatic promotions."); setItems(Array.isArray(ab)?ab:[]); const pb=await p.json().catch(()=>[]),cb=await c.json().catch(()=>[]); setProducts(Array.isArray(pb)?pb.map((x:Option)=>({id:x.id,name:x.name})):[]); setCategories(Array.isArray(cb)?cb.map((x:Option)=>({id:x.id,name:x.name})):[]);},[]);
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Load failed."));},[load]);
 const toggle=(field:"productIds"|"categoryIds",id:string)=>setDraft(d=>({...d,[field]:d[field].includes(id)?d[field].filter(x=>x!==id):[...d[field],id]}));
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage(null);try{const payload={name:draft.name.trim(),description:draft.description.trim()||undefined,discountType:draft.discountType,value:draft.discountType==="PERCENTAGE"?parseInt(draft.value,10):cents(draft.value),minSubtotalCents:cents(draft.minSubtotal),maxDiscountCents:draft.maxDiscount?cents(draft.maxDiscount):null,startsAt:draft.startsAt?new Date(draft.startsAt).toISOString():null,endsAt:draft.endsAt?new Date(draft.endsAt).toISOString():null,priority:parseInt(draft.priority||"0",10),isActive:draft.isActive,productIds:draft.productIds,categoryIds:draft.categoryIds}; const r=await fetch(editing?`/api/staff/promotions/automatic/${editing}`:"/api/staff/promotions/automatic",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.message??"Unable to save promotion.");setDraft(blank);setEditing(null);setMessage("Automatic promotion saved.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false)}}
 function edit(x:Promotion){setEditing(x.id);setDraft({name:x.name,description:x.description??"",discountType:x.discountType,value:x.discountType==="PERCENTAGE"?String(x.value):(x.value/100).toFixed(2),minSubtotal:(x.minSubtotalCents/100).toFixed(2),maxDiscount:x.maxDiscountCents==null?"":(x.maxDiscountCents/100).toFixed(2),startsAt:dt(x.startsAt),endsAt:dt(x.endsAt),priority:String(x.priority),isActive:x.isActive,productIds:x.productIds,categoryIds:x.categoryIds});window.scrollTo({top:0,behavior:"smooth"});}
 async function deactivate(id:string){if(!confirm("Deactivate this automatic promotion?"))return;setBusy(true);const r=await fetch(`/api/staff/promotions/automatic/${id}/deactivate`,{method:"POST"});setBusy(false);if(r.ok){setMessage("Promotion deactivated.");await load();}else{const b=await r.json().catch(()=>null);setMessage(b?.message??"Unable to deactivate.");}}
 return <main className={styles.shell}><StaffNav active="promotions"/><header className={styles.header}><div><span className={styles.eyebrow}>PROMOTIONS</span><h1>Automatic discounts</h1><p>Apply the best eligible discount at checkout without a coupon code. Automatic discounts and coupons do not stack; the larger discount wins.</p><Link href="/staff/promotions">Manage coupon codes</Link></div></header>{message?<div className={styles.success}>{message}</div>:null}
 <section className={styles.editorGrid}><form className={styles.panel} onSubmit={save}><div className={styles.panelHeading}><div><h2>{editing?"Edit automatic promotion":"Create automatic promotion"}</h2><p>Server-authoritative rules are evaluated inside the checkout transaction.</p></div></div><div className={styles.formGrid}>
 <label><span>Name</span><input required value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label><label><span>Discount type</span><select value={draft.discountType} onChange={e=>setDraft(d=>({...d,discountType:e.target.value as Draft["discountType"]}))}><option value="PERCENTAGE">Percentage</option><option value="FIXED_AMOUNT">Fixed amount</option></select></label><label><span>{draft.discountType==="PERCENTAGE"?"Percentage (%)":"Amount (RM)"}</span><input required value={draft.value} onChange={e=>setDraft(d=>({...d,value:e.target.value}))}/></label><label><span>Minimum subtotal (RM)</span><input value={draft.minSubtotal} onChange={e=>setDraft(d=>({...d,minSubtotal:e.target.value}))}/></label><label><span>Maximum discount (RM)</span><input value={draft.maxDiscount} placeholder="Optional" onChange={e=>setDraft(d=>({...d,maxDiscount:e.target.value}))}/></label><label><span>Priority</span><input type="number" value={draft.priority} onChange={e=>setDraft(d=>({...d,priority:e.target.value}))}/></label><label><span>Starts at</span><input type="datetime-local" value={draft.startsAt} onChange={e=>setDraft(d=>({...d,startsAt:e.target.value}))}/></label><label><span>Ends at</span><input type="datetime-local" value={draft.endsAt} onChange={e=>setDraft(d=>({...d,endsAt:e.target.value}))}/></label><label className={styles.toggleLabel}><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft(d=>({...d,isActive:e.target.checked}))}/><span>Active</span></label><label className={styles.fullField}><span>Description</span><textarea rows={3} value={draft.description} onChange={e=>setDraft(d=>({...d,description:e.target.value}))}/></label></div>
 <div className={styles.scopeBlock}><div><strong>Eligible scope</strong><span>Leave both empty for the entire catalog.</span></div><div className={styles.scopeColumns}><div><strong>Categories</strong>{categories.map(x=><label className={styles.scopeCheck} key={x.id}><input type="checkbox" checked={draft.categoryIds.includes(x.id)} onChange={()=>toggle("categoryIds",x.id)}/><span>{x.name}</span></label>)}</div><div><strong>Products</strong>{products.map(x=><label className={styles.scopeCheck} key={x.id}><input type="checkbox" checked={draft.productIds.includes(x.id)} onChange={()=>toggle("productIds",x.id)}/><span>{x.name}</span></label>)}</div></div></div><div className={styles.panelActions}>{editing?<button type="button" className={styles.secondaryButton} onClick={()=>{setEditing(null);setDraft(blank)}}>Cancel</button>:null}<button disabled={busy}>{busy?"Saving…":"Save promotion"}</button></div></form>
 <aside className={styles.panel}><h2>Selection rule</h2><p className={styles.muted}>If multiple automatic promotions qualify, the highest monetary discount wins; priority breaks equal-discount ties. If a coupon is entered, checkout compares it with the best automatic promotion and gives the customer the larger discount.</p></aside></section>
 <section className={styles.panelSection}><div className={styles.panelHeading}><div><h2>Configured automatic promotions</h2><p>{items.length} rules</p></div></div>{items.map(x=><article className={styles.listCard} key={x.id}><div><strong>{x.name}</strong><p>{x.discountType==="PERCENTAGE"?`${x.value}% off`:`RM ${(x.value/100).toFixed(2)} off`} · min RM {(x.minSubtotalCents/100).toFixed(2)} · priority {x.priority} · {x.isActive?"Active":"Inactive"}</p></div><div className={styles.cardActions}><button className={styles.secondaryButton} onClick={()=>edit(x)}>Edit</button>{x.isActive?<button className={styles.secondaryButton} disabled={busy} onClick={()=>void deactivate(x.id)}>Deactivate</button>:null}</div></article>)}</section></main>;
}
