"use client";

import { useCallback, useEffect, useState } from "react";
import { StaffNav } from "./staff-nav";
import styles from "./staff-console.module.css";

type RefundCase = { id:string; orderNumber:string; customerName:string; email:string; reason:string; customerNote:string|null; amountCents:number; currency:string; status:string; provider:string; requestedAt:string; failureMessage:string|null };
const statuses=["REQUESTED","ALL","PROCESSING","REFUNDED","REJECTED","FAILED"];
function money(e:RefundCase){return new Intl.NumberFormat("en-MY",{style:"currency",currency:e.currency}).format(e.amountCents/100)}

export function RefundsConsole(){
 const [status,setStatus]=useState("REQUESTED"),[items,setItems]=useState<RefundCase[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const q=status==="ALL"?"":`?status=${encodeURIComponent(status)}`;const res=await fetch(`/api/staff/refunds${q}`,{cache:"no-store"});const body=await res.json().catch(()=>null);if(!res.ok)throw new Error(body?.message??"Unable to load refunds.");setItems(Array.isArray(body)?body:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load refunds.")}finally{setLoading(false)}},[status]);
 useEffect(()=>{void load()},[load]);
 async function action(item:RefundCase,kind:"approve"|"reject"){let note="";if(kind==="approve"){if(!window.confirm(`Approve ${money(item)} refund for ${item.orderNumber}? This sends the refund to the original payment provider.`))return}else{note=window.prompt("Reason / staff note for rejection:","")??"";if(note===""&&!window.confirm("Reject without a note?"))return}setBusy(item.id);setError(null);try{const res=await fetch(`/api/staff/refunds/${encodeURIComponent(item.id)}/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({note})});const body=await res.json().catch(()=>null);if(!res.ok)throw new Error(body?.message??"Refund action failed.");await load()}catch(e){setError(e instanceof Error?e.message:"Refund action failed.")}finally{setBusy(null)}}
 return <main className={styles.shell}><StaffNav active="refunds"/><header className={styles.header}><div><span className={styles.eyebrow}>REFUND REVIEW</span><h1>Refund approvals</h1><p>Customer refund requests wait here until staff approves or rejects them.</p></div></header><section className={styles.order}><div className={styles.orderTop}><div><strong>Status</strong><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><button className={styles.secondaryLink} onClick={()=>void load()} disabled={loading}>Refresh</button></div></section>{error?<div className={styles.error}>{error}</div>:null}{loading?<div className={styles.empty}>Loading refunds…</div>:null}{!loading&&items.length===0?<div className={styles.empty}>No refund requests match this filter.</div>:null}<div className={styles.list}>{items.map(item=><section className={styles.order} key={item.id}><div className={styles.orderTop}><div><h2>{item.orderNumber}</h2><p>{item.customerName} · {item.email}</p></div><div className={styles.badges}><span>{item.status}</span></div></div><div className={styles.orderBody}><div><strong>{item.reason}</strong><p>{item.customerNote||"No customer note."}</p><p>{item.provider} · {new Date(item.requestedAt).toLocaleString("en-MY")}</p>{item.failureMessage?<p>{item.failureMessage}</p>:null}</div><strong className={styles.total}>{money(item)}</strong></div>{item.status==="REQUESTED"?<div className={styles.headerActions}><button className={styles.secondaryLink} disabled={busy===item.id} onClick={()=>void action(item,"reject")}>Reject</button><button className={styles.secondaryLink} disabled={busy===item.id} onClick={()=>void action(item,"approve")}>{busy===item.id?"Working…":"Approve refund"}</button></div>:null}</section>)}</div></main>
}
